name: 🚀 Run

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    name: 🚀 Run
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚀 Run
        shell: bash
        run: |
          python3 main.py

  test:
    name: 🧪 Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🧪 Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 🧪 Run Unit Tests
        run: |
          python3 -m unittest discover
